spring.application.name=backend

spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.feiuvwqkdecjvtwtmsnt
spring.datasource.password=IzTMbCxCtTocoRVX
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=SKb2EvW1t8XW1QfW1Yd4yym1q/B+ApCv+dxdyobRrII
jwt.expiration=86400000

supabase.url=https://feiuvwqkdecjvtwtmsnt.supabase.co
supabase.storage.bucket=resources
supabase.service.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlaXV2d3FrZGVjanZ0d3Rtc250Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NzMzMzUxNiwiZXhwIjoyMTAyOTA5NTE2fQ.rV3q3mTCZQnf7cokbzYY6DsI-hZ1__j97ooomiHGpJ8

spring.profiles.active=local