spring.application.name=backend

spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.feiuvwqkdecjvtwtmsnt
spring.datasource.password=IzTMbCxCtTocoRVX
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=SKb2EvW1t8XW1QfW1Yd4yym1q/B+ApCv+dxdyobRrII
jwt.expiration=86400000

supabase.url=https://feiuvwqkdecjvtwtmsnt.supabase.co
supabase.storage.bucket=resources
supabase.service.key=sb_secret__Is8SdCMQ_FBkoBrf80Zew_jy5HezV2

spring.profiles.active=local